### ISSUE TITLE
Add Support for Custom Binary Publishing mechanism

### ISSUE THREAD

**Issue by spicy-santos** [dd4t/DD4T.TridionTemplates#4]
Sometimes it is necessary to publish binaries to a custom location or even with a custom file name depending on certain rules. It would be great if we could define custom binary publishing mechanisms per template. Some of these reasons are SEO, image path needs to be meaningful as well as its file name; Security, maybe I need to secure certain pdf's based on some keywords. Currently I have to create my own build or own binary publish mechanism, and since v 2.0 of DD4T is now embedding Binary Publish in the JSON (former but still valid XML) generation TBB, it is even harder to decouple both functionalities. I did a fork and  have an example in my development branch (JaimeSA) with what I mean, I will try to merge the latest code with my branch.

**Comment by rogieroudshoorn** [comment]
You can inject your own BinaryPublisher into the BuildManager (per template!) which should provide a customization mechanism for however you'd like to construct your URL's that go into the JSON, and however you'd like to publish the binaries.

I would certainly be happy to have a discussion on how you extend this - i usually end up using this extension point in every project.

**Comment by quirijnslings** [comment]
Do you have some example source code?

**Comment by quirijnslings** [comment]
We will do this after GA.
@rogieroudshoorn could you share some code from your previous project(s) please?

**Comment by quirijnslings** [comment]
@JaimeSA it took a bit longer than expected, but this is finally fixed. See http://blog.trivident.com/customizing-binary-paths-in-dd4t/.

**Comment by spicy-santos** [comment]
Bravo!
